# **연산자 끼워넣기**

N개의 수로 이루어진 수열이 주어진다.

또, 수와 수 사이에 끼워 넣을 수 있는 N-1개의 연산자가 주어진다. (연산자는 +, -, ×, ÷)

연산자를 넣어 수식을 만들 수 있는데 주어진 수의 순서를 바꾸면 안된다.

식의 계산은 우선순위를 무시하고 앞에서부터 진행하며, 나눗셈은 정수 나눗셈으로 몫만 취한다.

양수를 음수로 나눌 때에는 양수로 바꾼 뒤 몫을 취하고 그 몫을 음수로 바꾼다.

N개의 수와 N-1개의 연산자가 주어졌을 때, 만들 수 있는 식의 결과가 최대인 것과 최소인 것을 구하시오.

In [36]:
n = int(input())
data = list(map(int, input().split()))
oper = list(map(int, input().split()))  # +,-,x,/


result = {}
def operation(oper, value0, value1, select):
    # global oper
    # oper = oper

    result = {}
    for i in range(4):
        if oper[i] != 0:
            if i == 0:
                result[int(value0 + value1)] = 0
            elif i == 1:
                result[int(value0 - value1)] = 1
            elif i == 2:
                result[int(value0 * value1)] = 2
            elif i == 3:
                result[int(value0 /value1)] = 3

    if select == "max":
        value = max(result.keys())
        oper[result[value]] -= 1
        return value
    else:
        value = min(result.keys())
        oper[result[value]] -= 1
        return value




# value_max = data[0]
# for i in range(1, n):
#     value_max = operation(oper, value_max, data[i], "max")
#     print(value_max)

value_min = data[0]
for i in range(1, n):
    value_min = operation(oper, value_min, data[i], "min")
    print(value_min)

6
1 2 3 4 5 6
2 1 1 1
-1
-3
0
5
11

In [39]:
n = int(input())
data = list(map(int, input().split()))
add, sub, mul, div = map(int, input().split())

# 최솟값과 최댓값 초기화
min_value = 1e9
max_value = -1e9


# DFS code
def dfs(i, now):
    global min_value, max_value, add, sub, mul, div

    # 모든 연산자를 다 사용한 경우, 최솟값과 최댓값 업데이트
    if i == n:
        min_value = min(min_value, now)
        max_value = max(max_value, now)

    else:
        # 각 연산자에 대해 재귀적 수행
        if add > 0:
            add -= 1
            dfs(i+1, now + data[i])
            add += 1

        if sub > 0:
            sub -= 1
            dfs(i+1, now - data[i])
            sub += 1

        if mul > 0:
            mul -= 1
            dfs(i+1, now * data[i])
            mul += 1

        if div > 0:
            div -= 1
            dfs(i+1, int(now / data[i]))
            div += 1

dfs(1, data[0])

print(max_value)
print(min_value)

6
1 2 3 4 5 6
2 1 1 1
54
-24

0.75